name: Build Debian Package
description: |
  Builds the debian package represented by this repo at the ref pointed by the debain-ref argument.

on:
  workflow_dispatch:
    inputs:

      debian-ref:
        description: The debian ref to build. For example branch "debian/latest" or tag "debian/1.0.0-1"
        type: string
        required: true
        default: debian/latest

      ubuntu-codename:
        description: The ubuntu codename to build for. Ex noble, jammy, etc
        type: choice
        default: noble
        options:
          - noble
          - questing

      abi-checker:
        description: Run the ABI checker or not
        type: boolean
        default: false

      push-to-repo:
        description: Push to repository upon successful build
        type: boolean
        default: false

permissions:
 contents: read
 security-events: write

jobs:
  build:
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/qcom-build-debian-package-reusable-workflow.yml@development
    with:
      qcom-build-utils-ref: development
      debian-ref: ${{ inputs.debian-ref }}
      ubuntu-codename: ${{ inputs.ubuntu-codename }}
      run-abi-checker: ${{ inputs.abi-checker }}
      push-to-repo: ${{ inputs.push-to-repo }}
    secrets:
      TOKEN: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}